version: 2
updates:
  - package-ecosystem: composer
    directory: "/site"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    versioning-strategy: increase
    commit-message:
      prefix: "[Dependency] "
      prefix-development: "[DevDependency]"
  - package-ecosystem: npm
    directory: "/site"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "[Dependency] "
      prefix-development: "[DevDependency]"
  # Migration
  - package-ecosystem: pip
    directory: "/migration/migration_requirements.txt"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "[Dependency] "
      prefix-development: "[DevDependency]"
  # Auto-grader
  - package-ecosystem: pip
    directory: "/autograder/autograder_requirements.txt"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "[Dependency] "
      prefix-development: "[DevDependency]"
  # Setup scripts
  - package-ecosystem: pip
    directory: "/.setup/pip/system_requirements.txt"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "[Dependency] "
      prefix-development: "[DevDependency]"
