language: php
sudo: true
dist: trusty

cache:
  pip: true
  directories:
    - vendor
    - ${HOME}/.composer/cache
    - ${HOME}/.cache/pip

# We use build stages (https://docs.travis-ci.com/user/build-stages/) to allow us to
# create a matrix of firstly building and testing various PHP targets in several ways
# (lint, unit test, e2e test) and then test out various C++ compilers to ensure our
# best compatibility.
jobs:
  fast_finish: true
  allow_failures:
    - php: 7.2

  include:
    # Warm up the pip and composer caches to use it for the rest of the build stages
    - &00-cache
      stage: 00 warm up cache
      php: 7.0
      before_install: source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
      install:
        - travis_retry composer install --prefer-dist --no-interaction
        - pip3 install -U pip
        - pip3 install python-pam
        - pip3 install PyYAML
        - pip3 install psycopg2-binary
        - pip3 install sqlalchemy
        - pip3 install pylint_runner
        - pip3 install python-dateutil
        - pip3 install selenium
        - pip3 install pause
      script: skip
    - <<: *00-cache
      php: 7.1
    - <<: *00-cache
      php: 7.2

    - &04-integration
      stage: Integration test
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - g++-multilib
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
      before_install:
        - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
        - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
        - source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
      install:
        - sudo apt-get install -qqy build-essential automake cmake libseccomp2 seccomp libseccomp-dev valgrind
        - sudo apt-get install -qqy pkg-config flex bison poppler-utils libpcre3 libpcre3-dev unzip libboost-all-dev
        - pip3 install -U pip
        - pip3 install PyYAML
        - pip3 install python-dateutil
        - pushd ${TRAVIS_BUILD_DIR}/python_submitty_utils
        - python3 setup.py install
        - popd
        - sudo chmod -R 555 /usr/local/lib/python*/
        - sudo chmod -R 555 /opt/python/${PY_VERSION_3}/lib/python${PY_VERSION_3:0:3}/*
        - sudo ./.setup/travis/autograder.sh
        - ./.setup/travis/setup.sh
        - sudo ./.setup/travis/setup_test_suite.sh
      script: sudo /usr/local/submitty/test_suite/integrationTests/run.py
    - <<: *04-integration
      language: cpp
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - g++-multilib
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - <<: *04-integration
      language: cpp
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - g++-multilib
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

notifications:
  email: false
