language: php
sudo: true
dist: trusty

matrix:
  include:
    - php: 5.6
      env: AUTH_METHOD=DatabaseAuthentication INTEGRATION_SUITE=false
    - php: 7.0
      env: AUTH_METHOD=DatabaseAuthentication INTEGRATION_SUITE=false
    - php: 7.0
      env: AUTH_METHOD=PamAuthentication INTEGRATION_SUITE=false
    - php: 7.0
      env: AUTH_METHOD=DatabaseAuthentication INTEGRATION_SUITE=true

cache:
  pip: true
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.cache/pip
    # we should be catching this once we no longer use AnalysisTools make to install it
#    - $HOME/.stack

addons:
  postgresql: "9.5"
  apt:
    sources:
      - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
      - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
    # You cannot put just any Ubuntu trusty package here and expect to install them and that
    # they must be in this list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
    # otherwise you'll have to install it via "sudo apt-get install ..." in the before_install section
    packages:
      - apache2
      - libapache2-mod-fastcgi
      - build-essential
      - automake
      - cmake
      - clang
      - g++-multilib
      - libseccomp2
      - seccomp
      - libseccomp-dev
      - valgrind
      - pkg-config
      - flex
      - bison
      - poppler-utils
      - libpcre3
      - libpcre3-dev
      - unzip
      - google-chrome-stable
      - libpam-passwdqc
      - libboost-all-dev

before_install:
  - jdk_switcher use default
  - export PATH="$PATH:$HOME/.composer/vendor/bin:/usr/bin"
  - sudo sed -e "s?secure_path=\"?secure_path=\"/opt/python/2.7.12/bin:/opt/python/3.5.2/bin:${PATH}:?g" --in-place /etc/sudoers

install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.5" ]]; then sudo add-apt-repository -y ppa:ondrej/php; sudo apt-get -qq update; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then sudo apt-get -y install libapache2-mod-php5.6 php5.6-pgsql php5.6-curl; a2enmod php5.6; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo apt-get -y install libapache2-mod-php7.0 php7.0-pgsql php7.0-curl; a2enmod php7.0; fi
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - travis_retry composer install --prefer-dist --no-interaction
  - pip2 install -U pip
  - pip2 install xlsx2csv
  - pip2 install python-pam
  - pip2 install sqlalchemy
  - pip2 install psycopg2
  - pip2 install PyYAML
  - pip2 install selenium
  - pip2 install nose2
  - pip2 install unittest2
  - pip2 install pylint_runner
  - pip3 install -U pip
  - pip3 install python-pam
  - pip3 install psycopg2
  - pip3 install PyYAML
  - pip3 install sqlalchemy
  - sudo chmod -R 555 /usr/local/lib/python*/
  - sudo chmod -R 555 /opt/python/2.7.12/lib/python2.7/*
  - sudo chmod -R 555 /opt/python/3.5.2/lib/python3.5/*

before_script:
  # Doing this helps chromedriver from hanging for some mysterious reason
  # https://github.com/SeleniumHQ/docker-selenium/issues/87
  - export DBUS_SESSION_BUS_ADDRESS=/dev/null
  - psql -U postgres -c "CREATE ROLE hsdbu WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'hsdbu'"
  - sudo ./.setup/travis/autograder.sh
  - ./.setup/travis/setup.sh
  - if [ ${INTEGRATION_SUITE} = false ]; then sudo python /usr/local/submitty/GIT_CHECKOUT_Submitty/.setup/bin/setup_sample_courses.py csci1000; fi
  - sudo ./.setup/travis/setup_test_suite.sh
  - sudo sed -e "s?www-data?hwphp?g" --in-place /etc/apache2/envvars
  - sudo a2enmod include rewrite actions cgi alias headers
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo a2dissite 000-default
  - sudo rm -rf /etc/apache2/sites-available/*
  - sudo rm -rf /etc/apache2/sites-enabled/*
  - sudo cp -f .setup/travis/apache.conf /etc/apache2/sites-available/submitty.conf
  - sudo a2ensite submitty
  - sudo chown -R hwphp:hwphp /var/lib/apache2/fastcgi
  - sudo chmod -R 755 /usr/local/submitty
  - sudo chmod -R 777 /usr/local/submitty/test_suite
  - sudo bash -c 'echo "export PATH=$PATH" >> /etc/apache2/envvars'
  - sudo bash -c 'echo "export PATH=$PATH" >> /home/hwphp/.profile'
  - sudo bash -c 'echo "export PATH=$PATH" >> /home/hwphp/.bashrc'
  - sudo service apache2 restart
  #- ./.setup/travis/start.sh
  - sudo sed -e "s?debug = false?debug = true?g" --in-place /usr/local/submitty/site/config/master.ini
  - sudo sed -e "s?PamAuthentication?${AUTH_METHOD}?g" --in-place /usr/local/submitty/site/config/master.ini
  - sudo cat /usr/local/submitty/site/config/master.ini
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  # if these fail, travis fails
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  - vendor/bin/phpunit --version
  - if [ ${INTEGRATION_SUITE} = false ]; then vendor/bin/phpunit --configuration tests/phpunit.xml; fi
  - if [ ${INTEGRATION_SUITE} = false ]; then TEST_URL="http://localhost" nose2 -v --start-dir="tests/e2e"; fi
  - if [ ${INTEGRATION_SUITE} = true ]; then sudo python /usr/local/submitty/test_suite/integrationTests/run.py; fi

# Add more linters to the build process here
after_script:
  # Eventually this should be moved into the "script" once we've gotten the build to a point where all contained
  # python files will actually pass (which a lot right now will not)
  - pylint_runner -v ${TRAVIS_BUILD_DIR}
  - sudo ./.setup/travis/print_debug.sh
  # if this fails, it only prints, travis does not fail
  - sudo /usr/local/submitty/bin/check_everything.py

after_success:
  - travis_retry php vendor/bin/coveralls -v

notifications:
  email: false
