language: php
sudo: true
dist: trusty

jobs:
  include:
    - stage: lint
      php: 7.0
      script:
        - echo ${TRAVIS_BUILD_STAGE_NAME}
        - echo ${TRAVIS_PHP_VERSION}
    - php: 7.1
      script:
        - echo ${TRAVIS_BUILD_STAGE_NAME}
        - echo ${TRAVIS_PHP_VERSION}
    - php: 7.2
      script:
        - echo ${TRAVIS_BUILD_STAGE_NAME}
        - echo ${TRAVIS_PHP_VERSION}
    - stage: unit test
      php: 7.0
      script:
        - echo ${TRAVIS_BUILD_STAGE_NAME}
        - echo ${TRAVIS_PHP_VERSION}
    - php: 7.1
      script:
        - echo ${TRAVIS_BUILD_STAGE_NAME}
        - echo ${TRAVIS_PHP_VERSION}
    - php: 7.2
      script:
        - echo ${TRAVIS_BUILD_STAGE_NAME}
        - echo ${TRAVIS_PHP_VERSION}
    - stage: e2e test
      php: 7.0
      script:
        - echo ${TRAVIS_BUILD_STAGE_NAME}
        - echo ${TRAVIS_PHP_VERSION}
    - php: 7.1
      script:
        - echo ${TRAVIS_BUILD_STAGE_NAME}
        - echo ${TRAVIS_PHP_VERSION}
    - php: 7.2
      script:
        - echo ${TRAVIS_BUILD_STAGE_NAME}
        - echo ${TRAVIS_PHP_VERSION}
    - stage: integration test
      php: 7.0
      script:
        - echo ${TRAVIS_BUILD_STAGE_NAME}
        - echo ${TRAVIS_PHP_VERSION}

cache:
  pip: true
  directories:
    - vendor
    - ${HOME}/.composer/cache
    - ${HOME}/.cache/pip
