language: php
sudo: true
dist: trusty
php:
  - 5.5
  - 5.6
  - 7.0

cache:
  pip: true
  directories:
    - vendor
    - $HOME/.composer/cache
    - travis_phantomjs

addons:
  postgresql: "9.3"
  apt:
    sources:
      - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
      - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
    packages:
      - apache2
      - libapache2-mod-fastcgi
      - python
      - build-essential
      - automake
      - cmake
      - clang
      - g++-multilib
      - libseccomp2
      - seccomp
      - libseccomp-dev
      - valgrind
      - pkg-config
      - flex
      - bison
      - python3
      - libpcre3
      - libpcre3-dev

before_install:
   - export PHANTOMJS_VERSION=2.1.1
   - export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH
   - if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi
   - if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi
   - if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi
   - phantomjs --version
   - if [[ "$TRAVIS_PHP_VERSION" = "5.5" ]]; then mv composer_55.json composer.json; fi
   - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - psql -U postgres -c "create database submitty;"
  - psql -U postgres -c "CREATE GROUP submitty ROLE postgres"
  - psql -U postgres -c "CREATE ROLE hsdbu WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'hsdbu'"
  - psql -U postgres -d submitty -f site/data/tables.sql
  - psql -U postgres -d submitty -f tests/testData/travis.sql
  - sudo ./.setup/travis/autograder.sh
  - ./.setup/travis/setup.sh
  - sudo ./.setup/travis/setup_test_suite.sh
  - sudo usermod -a -G travis www-data
  - sudo usermod -a -G hwphp www-data
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo cp .setup/travis/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
  - sudo sed -e "s?www-data?hwphp?g" --in-place ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo sed -e "s?www-data?hwphp?g" --in-place /etc/apache2/envvars
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f .setup/travis/000-default.conf /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo chown -R hwphp:hwphp /var/lib/apache2/fastcgi
  - sudo chmod -R 755 /usr/local/submitty
  - sudo chmod -R 777 /usr/local/submitty/test_suite
  #- sudo chmod -R 755 /var/local/submitty
  - sudo ls -la /var/local/submitty
  - sudo ls -la /var/local/submitty/courses/f16/csci1000
  - sudo ls -la /var/local/submitty/courses/f16/csci1000/config
  - ./.setup/travis/start.sh
  - sudo service apache2 restart
  - sleep 5

script:
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  - vendor/bin/phpunit --version
  - BROWSER=phantomjs TEST_URL="http://localhost" vendor/bin/phpunit --configuration tests/phpunit.xml --no-coverage
  - python /usr/local/submitty/test_suite/integrationTests/run.py

after_script:
  - echo ${APACHE_LOG_DIR}
  - sudo tail -n 50 /var/log/apache2/submitty.log
  - sudo tail -n 50 /var/log/apache2/submitty-error.log

notifications:
  email: false
