language: php
sudo: true
dist: trusty
#we should switch to this after figuring out how to use newer version of PHPUnit
php:
#  - 5.5
  - 5.6
#  - 7.0

addons:
  postgresql: "9.3"

before_script:
#  - if [[ "$TRAVIS_PHP_VERSION" = "hhvm" ]]; then source ./.setup/travis/hhvm.sh; fi
  - if [[ "$TRAVIS_PHP_VERSION" = "5.5" ]]; then mv composer_55.json composer.json; fi
  - composer install
  - ./.setup/travis.sh
  - psql -c 'create database test_hwgrading;' -U postgres
  - psql --host=localhost --username=postgres --command="CREATE GROUP test_hwgrading ROLE postgres"
  - psql -f TAGradingServer/data/tables.sql -U postgres -d test_hwgrading
  - psql -f TAGradingServer/data/inserts.sql -U postgres -d test_hwgrading
  - psql -f tests/testData/travis.sql -U postgres -d test_hwgrading

script:
#  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
#  - vendor/phpunit/phpunit/phpunit --version
#  - vendor/phpunit/phpunit/phpunit --configuration tests/phpunit.xml
#  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then vendor/phpunit/phpunit/phpunit --configuration tests/phpunit_e2e.xml; fi
  - vendor/phpunit/phpunit/phpunit --configuration tests/phpunit_e2e.xml
#  - python /usr/local/hss/test_suite/integrationTests/scripts/run.py

after_script:
  - sudo ls /var/log/apache2
  - sudo cat /var/log/apache2/access.log
  - sudo cat /var/log/apache2/error.log
  - sudo ls -la ${TRAVIS_BUILD_DIR}

notifications:
  email: false