language: php
sudo: true
dist: trusty

cache:
  pip: true
  directories:
    - vendor
    - ${HOME}/.composer/cache
    - ${HOME}/.cache/pip

# We use build stages (https://docs.travis-ci.com/user/build-stages/) to allow us to
# create a matrix of firstly building and testing various PHP targets in several ways
# (lint, unit test, e2e test) and then test out various C++ compilers to ensure our
# best compatibility.
jobs:
  fast_finish: true
  allow_failures:
    - php: 7.2

  include:
    - &04-integration
      stage: Integration test
      language: cpp
      #addons:
      #  apt:
      #    sources:
      #      - ubuntu-toolchain-r-test
      #      - llvm-toolchain-precise-3.8
      #    packages:
      #      - clang-3.8
      #      - g++-multilib
      addons:
        apt:
          sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
          # You cannot put just any Ubuntu trusty package here and expect to install them and that
          # they must be in this list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
          # otherwise you'll have to install it via "sudo apt-get install ..." in the before_install section
          packages:
            - build-essential
            - automake
            - cmake
            - g++-multilib
            - libseccomp2
            - seccomp
            - libseccomp-dev
            - valgrind
            - pkg-config
            - flex
            - bison
            - poppler-utils
            - libpcre3
            - libpcre3-dev
            - unzip
            - libboost-all-dev
      env: CLANG_VER="5.0"
      before_install:
        - source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
        - source ${TRAVIS_BUILD_DIR}/.setup/travis/setup_llvm.sh
      install:
        - sudo apt-get install clang
        - source ${TRAVIS_BUILD_DIR}/.setup/travis/install_llvm.sh
        - pip3 install -U pip
        - pip3 install PyYAML
        - pip3 install python-dateutil
        - pushd ${TRAVIS_BUILD_DIR}/python_submitty_utils
        - python3 setup.py install
        - popd
        - sudo chmod -R 555 /usr/local/lib/python*/
        - sudo chmod -R 555 /opt/python/${PY_VERSION_3}/lib/python${PY_VERSION_3:0:3}/*
        - sudo ./.setup/travis/autograder.sh
        - ./.setup/travis/setup.sh
        - sudo ./.setup/travis/setup_test_suite.sh
      script:
        - sudo /usr/local/submitty/test_suite/integrationTests/run.py
        - ls -la /usr/local/submitty/tests/
    - <<: *04-integration
      env: CLANG_VER="6.0.0"

notifications:
  email: false
