language: php
sudo: true
dist: trusty

cache:
  pip: true
  directories:
    - vendor
    - ${HOME}/.composer/cache
    - ${HOME}/.cache/pip

# We use build stages (https://docs.travis-ci.com/user/build-stages/) to allow us to
# create a matrix of firstly building and testing various PHP targets in several ways
# (lint, unit test, e2e test) and then test out various C++ compilers to ensure our
# best compatibility.
jobs:
  fast_finish: true
  allow_failures:
    - php: 7.2

  include:
    # Warm up the pip and composer caches to use it for the rest of the build stages
    - &00-cache
      stage: 00 warm up cache
      php: 7.0
      before_install: source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
      install:
        - travis_retry composer install --prefer-dist --no-interaction
        - pip3 install -U pip
        - pip3 install python-pam
        - pip3 install PyYAML
        - pip3 install psycopg2-binary
        - pip3 install sqlalchemy
        - pip3 install pylint_runner
        - pip3 install python-dateutil
        - pip3 install selenium
      script: skip
    - <<: *00-cache
      php: 7.1
    - <<: *00-cache
      php: 7.2

    # Lint the codebase to ensure that the code is compliant to our system
    - &01-lint
      stage: 01 lint
      php: 7.0
      script:
        - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    - <<: *01-lint
      php: 7.1
    - <<: *01-lint
      php: 7.2

    - &02-unit
      stage: 02 unit test
      php: 7.0
      script:
        - vendor/bin/phpunit --version
        - vendor/bin/phpunit --configuration tests/phpunit.xml
      after_success:
        - travis_retry php vendor/bin/coveralls -v
    - <<: *02-unit
      php: 7.1
    - <<: *02-unit
      php: 7.2

    - &03-e2e
      stage: 03 e2e test
      php: 7.0
      addons:
        chrome: stable
        postgresql: "9.5"
        apt:
          sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
          packages:
            - apache2
            - libapache2-mod-fastcgi
            - build-essential
            - automake
            - cmake
            - clang
            - g++-multilib
            - libseccomp2
            - seccomp
            - libseccomp-dev
            - valgrind
            - pkg-config
            - flex
            - bison
            - poppler-utils
            - libpcre3
            - libpcre3-dev
            - unzip
            - google-chrome-stable
            - libpam-passwdqc
            - libboost-all-dev
      before_install: source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
      install:
        - pip3 install -U pip
        - pip3 install python-pam
        - pip3 install PyYAML
        - pip3 install psycopg2-binary
        - pip3 install sqlalchemy
        - pip3 install pylint_runner
        - pip3 install python-dateutil
        - pip3 install selenium
        - wget http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip
        - sudo chmod u+x chromedriver
        - sudo mv chromedriver /usr/bin/
        - pushd ${TRAVIS_BUILD_DIR}/python_submitty_utils
        - python3 setup.py install
        - popd
        - sudo chmod -R 555 /usr/local/lib/python*/
        - sudo chmod -R 555 /opt/python/${PY_VERSION_3}/lib/python${PY_VERSION_3:0:3}/*
      before_script:
        # Doing this helps chromedriver from hanging for some mysterious reason
        # https://github.com/SeleniumHQ/docker-selenium/issues/87
        - export DBUS_SESSION_BUS_ADDRESS=/dev/null
        - psql -U postgres -c "CREATE ROLE hsdbu WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'hsdbu'"
        - PGPASSWORD=hsdbu psql -d postgres -h localhost -U hsdbu -c "CREATE DATABASE submitty"
        - PGPASSWORD=hsdbu psql -d submitty -h localhost -U hsdbu -f ${TRAVIS_BUILD_DIR}/site/data/submitty_db.sql
        - sudo ./.setup/travis/autograder.sh
        - ./.setup/travis/setup.sh
        - sudo /usr/local/submitty/GIT_CHECKOUT_Submitty/.setup/bin/setup_sample_courses.py sample
        - sudo ./.setup/travis/setup_test_suite.sh
        - sudo sed -e "s?www-data?hwphp?g" --in-place /etc/apache2/envvars
        - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
        - sudo cp ${TRAVIS_BUILD_DIR}/.setup/travis/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
        - sudo a2enmod rewrite rewrite actions fastcgi alias headers
        - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
        - sudo chown -R travis:travis /var/lib/apache2/fastcgi
        - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
        - sudo a2dissite 000-default
        - sudo rm -rf /etc/apache2/sites-available/*
        - sudo rm -rf /etc/apache2/sites-enabled/*
        - sudo cp -f .setup/travis/apache.conf /etc/apache2/sites-available/submitty.conf
        - sudo a2ensite submitty
        - sudo chown -R hwphp:hwphp /var/lib/apache2/fastcgi
        - sudo chmod -R 755 /usr/local/submitty
        - sudo chmod -R 777 /usr/local/submitty/test_suite
        - sudo bash -c 'echo "export PATH=$PATH" >> /etc/apache2/envvars'
        - sudo bash -c 'echo "export PATH=$PATH" >> /home/hwphp/.profile'
        - sudo bash -c 'echo "export PATH=$PATH" >> /home/hwphp/.bashrc'
        - sudo service apache2 restart
        #- ./.setup/travis/start.sh
        - sudo cat /usr/local/submitty/site/config/master.ini
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
      script:
        - TEST_URL="http://localhost" python -m unittest discover -v
    - <<: *03-e2e
      php: 7.1
    - <<: *03-e2e
      php: 7.2

    - &04-integration
      stage: Integration test
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_install:
        - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
        - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
        - source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
      install:
        - sudo apt-get install -qqy build-essential automake cmake libseccomp2 seccomp libseccomp-dev valgrind
        - sudo apt-get install -qqy pkg-config flex bison poppler-utils libpcre3 libpcre3-dev unzip libboost-all-dev
        - pip3 install -U pip
        - pip3 install PyYAML
        - pip3 install python-dateutil
        - ./.setup/travis/setup.sh
        - sudo ./.setup/travis/setup_test_suite.sh
      script: sudo /usr/local/submitty/test_suite/integrationTests/run.py
    - <<: *04-integration
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - <<: *04-integration
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - <<: *04-integration
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - g++-multilib
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
    - <<: *04-integration
      language: cpp
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - g++-multilib
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - <<: *04-integration
      language: cpp
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - g++-multilib
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

notifications:
  email: false
