language: php
sudo: true
dist: xenial

cache:
  pip: true
  directories:
    - ${TRAVIS_BUILD_DIR}/site/vendor
    - ${HOME}/.composer/cache
    - ${HOME}/.cache/pip

# We use build stages (https://docs.travis-ci.com/user/build-stages/) to allow us to
# create a matrix of firstly building and testing various PHP targets in several ways
# (lint, unit test, e2e test) and then test out various C++ compilers to ensure our
# best compatibility.
jobs:
  fast_finish: true

  include:
    - &03-e2e
      stage: 03 e2e test
      php: 7.2
      env: AUTH_METHOD=1
      services:
        - xvfb
        - docker
      addons:
        chrome: stable
        postgresql: "9.5"
        apt:
          sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
          packages:
            - apache2
            - libapache2-mod-fastcgi
            - apache2-suexec-custom
            - libapache2-mod-authnz-external
            - libapache2-mod-authz-unixgroup
            - libapache2-mod-wsgi-py3
            - build-essential
            - automake
            - cmake
            - clang
            - g++-multilib
            - libseccomp2
            - seccomp
            - libseccomp-dev
            - valgrind
            - pkg-config
            - flex
            - bison
            - poppler-utils
            - libpcre3
            - libpcre3-dev
            - unzip
            - google-chrome-stable
            - libpam-passwdqc
            - libboost-all-dev
      before_install: source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
      install:
        - PHP_VERSION=${TRAVIS_PHP_VERSION:0:3}
        - sudo add-apt-repository -y ppa:ondrej/php; sudo apt-get -qq update;
        - sudo apt-get -y install libapache2-mod-php${PHP_VERSION} php${PHP_VERSION}-pgsql php${PHP_VERSION}-curl; a2enmod php${PHP_VERSION};
        - pip3 install -U pip
        - pip3 install python-pam
        - pip3 install PyYAML
        - pip3 install psycopg2-binary
        - pip3 install sqlalchemy
        - pip3 install pylint_runner
        - pip3 install python-dateutil
        - pip3 install selenium
        - pip3 install pause
        - pip3 install paramiko
        - pip3 install psutil
        - CHROME_VERSION=$(google-chrome --version | egrep -o -e '[0-9]+\.[0-9]+\.[0-9]+')
        - CHROME_DRIVER_VERSION=$(curl -L https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
        - wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip
        - sudo chmod u+x chromedriver
        - sudo mv chromedriver /usr/bin/
        - pushd ${TRAVIS_BUILD_DIR}/python_submitty_utils
        - pip3 install .
        - popd
      before_script:
        # Need to make this a full repo so that we can get the tag information
        # when we're installing
        - git fetch --unshallow
        - git fetch
        # Doing this helps chromedriver from hanging for some mysterious reason
        # https://github.com/SeleniumHQ/docker-selenium/issues/87
        - export DBUS_SESSION_BUS_ADDRESS=/dev/null
        - psql -U postgres -c "CREATE ROLE submitty_dbuser WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'submitty_dbuser'"
        - PGPASSWORD=submitty_dbuser psql -d postgres -h localhost -U submitty_dbuser -c "CREATE DATABASE submitty"
        - sudo bash .setup/travis/autograder.sh
        - sudo bash .setup/travis/setup.sh
        - sudo python3 /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/setup_sample_courses.py --no_submissions sample
        - sudo bash .setup/travis/setup_test_suite.sh
        - sudo sed -e "s?www-data?submitty_php?g" --in-place /etc/apache2/envvars
        - sudo a2enmod include rewrite actions cgi alias headers fastcgi suexec authnz_external headers proxy_fcgi
        - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - cp .setup/php-fpm/pool.d/submitty.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
        - sudo mkdir /run/php
        - sudo chown www-data:www-data /run/php
        - sudo chmod 755 /run/php
        - sudo ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
        - sudo a2dissite 000-default
        - sudo rm -rf /etc/apache2/sites-available/*
        - sudo rm -rf /etc/apache2/sites-enabled/*
        - sudo cp -f .setup/vagrant/sites-available/submitty.conf /etc/apache2/sites-available/submitty.conf
        - sudo sed -e "s?SUBMITTY_URL?*?g" --in-place /etc/apache2/sites-available/submitty.conf
        - sudo sed -e "s?Require ip *??g" --in-place /etc/apache2/sites-available/submitty.conf
        - sudo a2ensite submitty
        - sudo chown -R submitty_php:submitty_php /var/lib/apache2/fastcgi
        # TODO: Figure out why these chmod's are necessary and fix whatever has
        #       bad permission (https://github.com/Submitty/Submitty/issues/1040)
        - sudo chmod -R 755 /usr/local/submitty
        - sudo chmod -R 777 /usr/local/submitty/test_suite
        - sudo chown root:submitty_daemon  /usr/local/submitty/sbin/untrusted_execute
        - sudo chmod 4550 /usr/local/submitty/sbin/untrusted_execute
        - sudo bash -c 'echo "export PATH=$PATH" >> /etc/apache2/envvars'
        - cat /etc/apache2/sites-available/submitty.conf
        - sudo apache2ctl -t
        - sudo service apache2 restart
      script:
        - TEST_URL="http://localhost" python -m unittest discover -v --start-directory tests


notifications:
  email: false
  slack:
    secure: A/rJsHlznzryxJEvULY9C8kCB9x+9IrRSnIIOutEoptAOyxb44FP5Lenact0ipeJxJIbSL667C/5F2J+e78METDhQD1xlCTcUG3FoonSmnqTvj73edeR8YoMuRchLRsxw2bcdKA+bv0fKzS9bPzrXOJTykunprmKSDkDlNjFHaY=
