language: php
sudo: true
dist: trusty

jobs:
  include:
    - stage: Lint
      php: 7.0
      addons:
        postgresql: "9.5"
      before_install: 
        - source ${TRAVIS_BUILD_DIR}/travis/before_install.sh
      install:
        - source ${TRAVIS_BUILD_DIR}/travis/install.sh
      before_script:
        - source ${TRAVIS_BUILD_DIR}/travis/before_script.sh
      script:
        - source ${TRAVIS_BUILD_DIR}/travis/script.sh
      after_script:
        - source ${TRAVIS_BUILD_DIR}/travis/after_script.sh
    - php: 7.1
      before_install: 
        - source ${TRAVIS_BUILD_DIR}/travis/before_install.sh
      install:
        - source ${TRAVIS_BUILD_DIR}/travis/install.sh
      before_script:
        - source ${TRAVIS_BUILD_DIR}/travis/before_script.sh
      script:
        - source ${TRAVIS_BUILD_DIR}/travis/script.sh
      after_script:
        - source ${TRAVIS_BUILD_DIR}/travis/after_script.sh
    - php: 7.2
      before_install: 
        - source ${TRAVIS_BUILD_DIR}/travis/before_install.sh
      install:
        - source ${TRAVIS_BUILD_DIR}/travis/install.sh
      before_script:
        - source ${TRAVIS_BUILD_DIR}/travis/before_script.sh
      script:
        - source ${TRAVIS_BUILD_DIR}/travis/script.sh
      after_script:
        - source ${TRAVIS_BUILD_DIR}/travis/after_script.sh
    - stage: Unit_Test
      php: 7.0
      before_install: 
        - source ${TRAVIS_BUILD_DIR}/travis/before_install.sh
      install:
        - source ${TRAVIS_BUILD_DIR}/travis/install.sh
      before_script:
        - source ${TRAVIS_BUILD_DIR}/travis/before_script.sh
      script:
        - source ${TRAVIS_BUILD_DIR}/travis/script.sh
      after_script:
        - source ${TRAVIS_BUILD_DIR}/travis/after_script.sh
    - php: 7.1
      before_install: 
        - source ${TRAVIS_BUILD_DIR}/travis/before_install.sh
      install:
        - source ${TRAVIS_BUILD_DIR}/travis/install.sh
      before_script:
        - source ${TRAVIS_BUILD_DIR}/travis/before_script.sh
      script:
        - source ${TRAVIS_BUILD_DIR}/travis/script.sh
      after_script:
        - source ${TRAVIS_BUILD_DIR}/travis/after_script.sh
    - php: 7.2
      before_install: 
        - source ${TRAVIS_BUILD_DIR}/travis/before_install.sh
      install:
        - source ${TRAVIS_BUILD_DIR}/travis/install.sh
      before_script:
        - source ${TRAVIS_BUILD_DIR}/travis/before_script.sh
      script:
        - source ${TRAVIS_BUILD_DIR}/travis/script.sh
      after_script:
        - source ${TRAVIS_BUILD_DIR}/travis/after_script.sh
    - stage: E2E_Test
      php: 7.0
      before_install: 
        - source ${TRAVIS_BUILD_DIR}/travis/before_install.sh
      install:
        - source ${TRAVIS_BUILD_DIR}/travis/install.sh
      before_script:
        - source ${TRAVIS_BUILD_DIR}/travis/before_script.sh
      script:
        - source ${TRAVIS_BUILD_DIR}/travis/script.sh
      after_script:
        - source ${TRAVIS_BUILD_DIR}/travis/after_script.sh
    - php: 7.1
      before_install: 
        - source ${TRAVIS_BUILD_DIR}/travis/before_install.sh
      install:
        - source ${TRAVIS_BUILD_DIR}/travis/install.sh
      before_script:
        - source ${TRAVIS_BUILD_DIR}/travis/before_script.sh
      script:
        - source ${TRAVIS_BUILD_DIR}/travis/script.sh
      after_script:
        - source ${TRAVIS_BUILD_DIR}/travis/after_script.sh
    - php: 7.2
      before_install: 
        - source ${TRAVIS_BUILD_DIR}/travis/before_install.sh
      install:
        - source ${TRAVIS_BUILD_DIR}/travis/install.sh
      before_script:
        - source ${TRAVIS_BUILD_DIR}/travis/before_script.sh
      script:
        - source ${TRAVIS_BUILD_DIR}/travis/script.sh
      after_script:
        - source ${TRAVIS_BUILD_DIR}/travis/after_script.sh
    - stage: Integration_Test
      language: python
      python: 3.5
      before_install: 
        - source ${TRAVIS_BUILD_DIR}/travis/before_install.sh
      install:
        - source ${TRAVIS_BUILD_DIR}/travis/install.sh
      before_script:
        - source ${TRAVIS_BUILD_DIR}/travis/before_script.sh
      script:
        - source ${TRAVIS_BUILD_DIR}/travis/script.sh
      after_script:
        - source ${TRAVIS_BUILD_DIR}/travis/after_script.sh
    - stage: Integration_Test
      language: python
      python: 3.6
      before_install:
        - source ${TRAVIS_BUILD_DIR}/travis/before_install.sh
      install:
        - source ${TRAVIS_BUILD_DIR}/travis/install.sh
      before_script:
        - source ${TRAVIS_BUILD_DIR}/travis/before_script.sh
      script:
        - source ${TRAVIS_BUILD_DIR}/travis/script.sh
      after_script:
        - source ${TRAVIS_BUILD_DIR}/travis/after_script.sh

cache:
  pip: true
  directories:
    - vendor
    - ${HOME}/.composer/cache
    - ${HOME}/.cache/pip

notifications:
  email: false
