language: php
sudo: true
dist: trusty

cache:
  pip: true
  directories:
    - ${TRAVIS_BUILD_DIR}/site/vendor
    - ${HOME}/.composer/cache
    - ${HOME}/.cache/pip

# We use build stages (https://docs.travis-ci.com/user/build-stages/) to allow us to
# create a matrix of firstly building and testing various PHP targets in several ways
# (lint, unit test, e2e test) and then test out various C++ compilers to ensure our
# best compatibility.
jobs:
  fast_finish: true
  allow_failures:
    - php: 7.2

  include:

    - &03-e2e
      stage: 03 e2e test
      php: 7.0
      env: AUTH_METHOD=1
      addons:
        chrome: stable
        postgresql: "9.5"
        apt:
          sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
          packages:
            - apache2
            - libapache2-mod-fastcgi
            - build-essential
            - automake
            - cmake
            - clang
            - g++-multilib
            - libseccomp2
            - seccomp
            - libseccomp-dev
            - valgrind
            - pkg-config
            - flex
            - bison
            - poppler-utils
            - libpcre3
            - libpcre3-dev
            - unzip
            - google-chrome-stable
            - libpam-passwdqc
            - libboost-all-dev
      before_install: source ${TRAVIS_BUILD_DIR}/.setup/travis/before_install.sh
      install:
        - PHP_VERSION=${TRAVIS_PHP_VERSION:0:3}
        - sudo add-apt-repository -y ppa:ondrej/php; sudo apt-get -qq update;
        - sudo apt-get -y install libapache2-mod-php${PHP_VERSION} php${PHP_VERSION}-pgsql php${PHP_VERSION}-curl; a2enmod php${PHP_VERSION};
        - pip3 install -U pip
        - pip3 install python-pam
        - pip3 install PyYAML
        - pip3 install psycopg2-binary
        - pip3 install sqlalchemy
        - pip3 install pylint_runner
        - pip3 install python-dateutil
        - pip3 install selenium
        - pip3 install pause
        - wget http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip
        - sudo chmod u+x chromedriver
        - sudo mv chromedriver /usr/bin/
        - pushd ${TRAVIS_BUILD_DIR}/python_submitty_utils
        - python3 setup.py install
        - popd
        - sudo chmod -R 555 /usr/local/lib/python*/
        - sudo chmod -R 555 /opt/python/${PY_VERSION_3}/lib/python${PY_VERSION_3:0:3}/*
      before_script:
        # Doing this helps chromedriver from hanging for some mysterious reason
        # https://github.com/SeleniumHQ/docker-selenium/issues/87
        - export DBUS_SESSION_BUS_ADDRESS=/dev/null
        - psql -U postgres -c "CREATE ROLE hsdbu WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'hsdbu'"
        - PGPASSWORD=hsdbu psql -d postgres -h localhost -U hsdbu -c "CREATE DATABASE submitty"
        - PGPASSWORD=hsdbu psql -d submitty -h localhost -U hsdbu -f ${TRAVIS_BUILD_DIR}/site/data/submitty_db.sql
        - sudo ./.setup/travis/autograder.sh
        - ./.setup/travis/setup.sh
        - sudo /usr/local/submitty/GIT_CHECKOUT_Submitty/.setup/bin/setup_sample_courses.py sample
        - sudo ./.setup/travis/setup_test_suite.sh
        - sudo sed -e "s?www-data?hwphp?g" --in-place /etc/apache2/envvars
        - sudo a2enmod include rewrite actions cgi alias headers
        - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - sudo a2dissite 000-default
        - sudo rm -rf /etc/apache2/sites-available/*
        - sudo rm -rf /etc/apache2/sites-enabled/*
        - sudo cp -f .setup/travis/apache.conf /etc/apache2/sites-available/submitty.conf
        - sudo a2ensite submitty
        - sudo chown -R hwphp:hwphp /var/lib/apache2/fastcgi
        - sudo chmod -R 755 /usr/local/submitty
        - sudo chmod -R 777 /usr/local/submitty/test_suite
        - sudo bash -c 'echo "export PATH=$PATH" >> /etc/apache2/envvars'
        - sudo bash -c 'echo "export PATH=$PATH" >> /home/hwphp/.profile'
        - sudo bash -c 'echo "export PATH=$PATH" >> /home/hwphp/.bashrc'
        - sudo service apache2 restart
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
      script:
        - echo ${PATH}
        - ls -la $(which composer)
        - sudo su - hwphp -c "which composer"
        - sudo su - hwphp -c "/home/travis/.phpenv/shims/composer --help"
        # - TEST_URL="http://localhost" python -m unittest discover -v --start-directory tests

notifications:
  email: false
