name: 'PR Title Check'
on:
  pull_request:
    # check when PR
    # * is created,
    # * title is edited, and
    # * new commits are added (to ensure failing title blocks merging)
    types: [ opened, edited, synchronize ]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: dylanvann/check-pull-request-title@v0.1.14
        with:
          #
          # pull request titles format rules here:
          # https://submitty.org/developer/how_to_contribute#how-to-make-a-pull-request-pr-to-submitty
          #
          # [<TYPE>:<MODULE> ] <SUBJECT>
          #
          pattern: '^\[(Bugfix|Feature|Refactor|Testing|Documentation|VPAT|UI/UX|Dependency):(Submission|Autograding|Forum|Notifications|TAGrading|InstructorUI|RainbowGrades|System|Developer|API)\] .{2,40}$'
