name: Submitty CI-2

on:
    push:

env:
  PGPASSWORD: submitty_dbuser
  PHP_USER: submitty_php
  PHP_GROUP: submitty_php
  CGI_USER: submitty_cgi
  SUBMITTY_DATA_DIR: /var/local/submitty
  SUBMITTY_INSTALL_DIR: /usr/local/submitty
  POSTGRES_HOST: localhost
  PHP_VER: 7.2


jobs:
    e2e:
        runs-on: ubuntu-18.04
        services:
          postgres:
            image: postgres
            env: 
              POSTGRES_PASSWORD: submitty_dbuser
              POSTGRES_USER: postgres
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 5432:5432

        steps:
          - name: Cancel Previous Runs
            uses: styfle/cancel-workflow-action@0.8.0
            with:
              access_token: ${{ github.token }}
          - uses: actions/checkout@v2
            with:
              path: SUBMITTY_CPY/
          - name: Copy Repo
            run: |
              # have to copy first, absolute paths not supported by actions/checkout@v2
                sudo mkdir -p ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
                sudo cp -R SUBMITTY_CPY/. ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
                sudo chmod -R a+rwx  ${SUBMITTY_INSTALL_DIR}
                sudo chmod -R a+rwx /tmp/

          - uses: actions/setup-python@v2
            with:
              python-version: '3.6'
          - uses: shivammathur/setup-php@2.7.0
            with:
              extensions: imagick
              php-version: $PHP_VER
          - name: Cache pip
            uses: actions/cache@v2
            with:
              path: path ~/.cache/pip
              key: ${{ runner.os }}-py-pip-${{ hashFiles('**/requirements.txt') }}
              restore-keys: |
                ${{ runner.os }}-py-pip
          - name: Install python dependencies
            run: |
              python3 -m pip install --upgrade pip setuptools wheel  
              sudo python3 -m pip install --upgrade pip setuptools wheel
              pip3 -V
              sudo pip3 -V
              pip3 install cryptography
              pip3 install python-pam
              pip3 install sqlalchemy
              pip3 install selenium
              pip3 install tzlocal
              pip3 install jsonschema
              pip3 install jsonref
              pip3 install websocket_client
              pip3 install psycopg2
              pip3 install docker
              pip3 install pyyaml
              pip3 install selenium
              pip3 install websocket_client
              pip3 install python-pam
              pip3 install python-dateutil
              pip3 install paramiko
              pip3 install pyzbar
              pip3 install watchdog
              #needs to be globally available for all users
              sudo pip3 install docker
              sudo pip3 install paramiko
              sudo pip3 install tzlocal
              sudo pip3 install sqlalchemy
              sudo pip3 install jsonref
              sudo pip3 install numpy
              sudo pip3 install opencv-python
              sudo pip3 install pyPdf
              sudo apt-get install libzbar0
              sudo pip3 install pyzbar
              sudo pip3 install PyPDF2
              sudo pip3 install pdf2image
              sudo pip3 install onnxruntime
              sudo pip3 install watchdog
              sudo pip3 install python-dateutil
              sudo pip3 install psutil
              sudo pip3 install psycopg2
              sudo pip3 install python-pam
              sudo pip3 install sqlalchemy
          - name: Get composer cache dir
            id: composer-cache
            run: |
              pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty/site
              echo "::set-output name=dir::$(composer config cache-files-dir)"
              popd
          - name: Install composer Cache
            uses: actions/cache@v2
            with:
              path: ${{ steps.composer-cache.outputs.dir }}
              key: ${{ runner.os }}-php-composer-${{ hashFiles('**/composer.lock') }}
              restore-keys: |
                ${{ runner.os }}-php-composer-
          - name: Install PHP dependencies
            run: |
              pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty/site
              composer install --prefer-dist
              popd
          - name: Install Submitty python utils
            run: |
              export SUBMITTY_INSTALL_DIR=/usr/local/submitty 
              export SUBMITTY_REPOSITORY=${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              pushd ${SUBMITTY_REPOSITORY}/python_submitty_utils
              pip3 install .
              pip3 show submitty_utils
              sudo apt-get install python3-setuptools
              umask 022
              sudo -H pip3 install .
              sudo pip3 show submitty_utils
              popd
          - name: Install accessibility checker
            run: |
              wget https://github.com/validator/validator/releases/download/20.3.16/vnu.jar_20.3.16.zip
              unzip vnu.jar_20.3.16.zip
              sudo mv dist/vnu.jar /usr/bin/
          - name: Install Submitty and populate database
            run: |
              PGPASSWORD=${PGPASSWORD} psql -d postgres -h localhost -U postgres -c "CREATE ROLE submitty_dbuser WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'submitty_dbuser'"
              PGPASSWORD=${PGPASSWORD} psql -d postgres -h localhost -U submitty_dbuser -c "CREATE DATABASE submitty"
              sudo apt-get update
              sudo apt-get install libseccomp-dev
              sudo apt-get install libboost-all-dev
              sudo apt-get install apache2
              sudo apt-get install apache2-suexec-custom
              sudo apt-get install libapache2-mod-authnz-external
              sudo apt-get install libapache2-mod-authz-unixgroup
              sudo apt-get install libapache2-mod-wsgi-py3
              sudo apt-get install nginx
              sudo apt-get install php${PHP_VER}-fpm
              export SUBMITTY_INSTALL_DIR=/usr/local/submitty #need to export otherwise shell scripts don't have access
              export SUBMITTY_REPOSITORY=${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              sudo -E env "PATH=$PATH" bash .setup/testing/autograder.sh
              sudo -E env "PATH=$PATH" bash .setup/testing/setup.sh
              popd
          - name: Install, configure and serve Submitty site
            run: |
              export SUBMITTY_INSTALL_DIR=/usr/local/submitty 
              export SUBMITTY_REPOSITORY=${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              sudo chmod -R a+rwx ${SUBMITTY_DATA_DIR}
              pushd ${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              sudo -E env "PATH=$PATH" python3 /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/setup_sample_courses.py --no_submissions sample
              sudo -E env "PATH=$PATH" bash .setup/testing/setup_test_suite.sh
              sudo a2enmod include rewrite actions cgi alias headers suexec authnz_external headers proxy_fcgi proxy_http proxy_wstunnel
              sudo cp .setup/php-fpm/pool.d/submitty.conf /etc/php/$PHP_VER/fpm/php-fpm.conf
              sudo mkdir -p /run/php
              sudo chown www-data:www-data /run/php
              sudo chmod 755 /run/php
              sudo a2dissite 000-default
              sudo rm -rf /etc/apache2/sites-available/*
              sudo rm -rf /etc/apache2/sites-enabled/*
              sudo cp -f .setup/apache/submitty.conf /etc/apache2/sites-available/submitty.conf
              sudo sed -e "s/Require host __your_domain__/Require all granted/g" --in-place /etc/apache2/sites-available/submitty.conf
              sudo cp .setup/apache/www-data /etc/apache2/suexec/www-data
              sudo chmod 0640 /etc/apache2/suexec/www-data
              sudo a2ensite submitty
              sudo bash -c 'echo "export PATH=$PATH" >> /etc/apache2/envvars'
              sudo apache2ctl -t
              sudo service php${PHP_VER}-fpm restart
              sudo service apache2 restart
              sudo mkdir /etc/systemd/system/nginx.service.d
              sudo printf "[Service]\nExecStartPost=/bin/sleep 0.1\n" | sudo tee /etc/systemd/system/nginx.service.d/override.conf
              sudo systemctl daemon-reload
              sudo rm -rf /etc/nginx/sites-available/*
              sudo rm -rf /etc/nginx/sites-enabled/*
              sudo cp -f .setup/nginx/submitty.conf /etc/nginx/sites-available/submitty.conf
              sudo chmod 644 /etc/nginx/sites-available/submitty.conf
              sudo ln -s /etc/nginx/sites-available/submitty.conf /etc/nginx/sites-enabled/submitty.conf
              sudo service nginx restart
          - uses: nanasess/setup-chromedriver@master
          - name: Run tests
            run: |
              sudo journalctl --rotate
              sudo journalctl --vacuum-time=1s
              sudo systemctl restart submitty_autograding_worker
              sudo systemctl restart submitty_autograding_shipper
              export DISPLAY=:99
              chromedriver --url-base=/wd/hub &
              sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
              export SUBMITTY_INSTALL_DIR=/usr/local/submitty 
              export SUBMITTY_REPOSITORY=${SUBMITTY_INSTALL_DIR}/GIT_CHECKOUT/Submitty
              pushd ${SUBMITTY_REPOSITORY}
              sudo sed -ie "s/Pam/Database/g" ${SUBMITTY_INSTALL_DIR}/config/database.json
              echo "Authentication Method => $(sudo jq -r ".authentication_method" /usr/local/submitty/config/database.json)"
              TEST_URL="http://localhost" python3 -m unittest discover -v --start-directory tests
              sudo bash tests/test_site_error_log.sh


      
